config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/home', to: 'pages#home'

  resources :recipes do
    member do
      post 'like'
    end
  end

  resources :chefs, except: [:new, :destroy]
  get '/register', to: 'chefs#new'

  #login and logout
  get '/login', to: 'logins#new'
  post '/login', to: 'logins#create'
  get '/logout', to: 'logins#destroy'

  resources :styles, only: [:new, :create, :show]
  resources :ingredients, only: [:new, :create, :show]
end

app/models/chef.rb
class Chef < ActiveRecord::Base
  # CALLBACKS
  before_save { self.email = email.downcase }

  # ASSOCIATIONS
  has_many :recipes
  has_many :likes

  # VALIDATIONS
  validates :chefname, presence: true, length: { minimum: 2, maximum: 40 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: VALID_EMAIL_REGEX }

  has_secure_password
end

app/models/ingredient.rb
class Ingredient < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :chef
  belongs_to :recipe

  validates_uniqueness_of :chef, scope: :recipe
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  # ASSOCIATIONS
  belongs_to :chef
  has_many :likes, dependent: :destroy
  has_many :recipe_styles, dependent: :destroy
  has_many :styles, through: :recipe_styles
  has_many :recipe_ingredients, dependent: :destroy
  has_many :ingredients, through: :recipe_ingredients

  # VALIDATIONS
  validates :chef_id, presence: true
  validates :name, presence: true, length: { minimum: 5, maximum: 100 }
  validates :summary, presence: true, length: { minimum:10, maximum: 150 }
  validates :description, presence: true, length: { minimum: 20, maximum: 500 }
  validate :picture_size
  default_scope -> { order(updated_at: :desc) }

  mount_uploader :picture, PictureUploader

  def thumbs_up_total
    self.likes.where(like: true).size
  end

  def thumbs_down_total
    self.likes.where(like: false).size
  end

  private
  def picture_size
    if picture.size > 5.megabytes
      errors.add(:picture, 'should be less than 5MB')
    end
  end
end

app/models/recipe_ingredient.rb
class RecipeIngredient < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :ingredient
end

app/models/recipe_style.rb
class RecipeStyle < ActiveRecord::Base
  belongs_to :recipe
  belongs_to :style
end

app/models/style.rb
class Style < ActiveRecord::Base
  validates :name, presence: true, length: { minimum: 2, maximum: 25 }
  has_many :recipe_styles
  has_many :recipes, through: :recipe_styles
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= Chef.find(session[:chef_id]) if session[:chef_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:danger] = 'You must be logged in to perform that action!'
      redirect_to recipes_path
    end
  end
end

app/controllers/chefs_controller.rb
class ChefsController < ApplicationController
  before_action :set_chef, only: [:edit, :update, :show]
  before_action :require_same_user, only: [:edit, :update]

  def index
    @chefs = Chef.paginate(page: params[:page], per_page: 3)
  end

  def new
    @chef = Chef.new
  end

  def create
    @chef = Chef.new(chef_params)
    if @chef.save
      flash[:success] = "Your account was successfully created"
      session[:chef_id] = @chef.id
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @chef.update(chef_params)
      flash[:success] = "You have updated your profile successfully!"
      redirect_to chef_path(@chef)
    else
      flash[:failure] = "Your profile did not update"
      render 'edit'
    end
  end

  def show
    @recipes = @chef.recipes.paginate(page: params[:page], per_page: 3)
  end

  private
  def chef_params
    params.require(:chef).permit(:chefname, :email, :password)
  end

  def require_same_user
    if current_user != @chef
      flash[:danger] = 'You can only edit your own profile'
      redirect_to root_path
    end
  end

  def set_chef
    @chef = Chef.find(params[:id])
  end
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :require_user, except: [:show]

  def show
    @ingredient = Ingredient.find(params[:id])
    @recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 4)
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:success] = 'Ingredient was created successfully'
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  private
  def ingredient_params
    params.require(:ingredient).permit(:name)
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
  def new

  end

  def create
    chef = Chef.find_by(email: params[:email])
    if chef && chef.authenticate(params[:password])
      session[:chef_id] = chef.id
      flash[:success] = 'You are logged in!'
      redirect_to recipes_path
    else
      flash.now[:danger] = 'Your email address or password does not match'
      render 'new'
    end
  end

  def destroy
    session[:chef_id] = nil
    flash[:success] = "You have logged out!"
    redirect_to root_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    redirect_to recipes_path if logged_in?
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:edit, :update, :show, :like]
  before_action :require_user, except: [:show, :index, :like]
  before_action :require_user_like, only: [:like]
  before_action :require_same_user, only: [:edit, :update]
  before_action :admin_user, only: :destroy

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 4)
  end

  def show
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_user

    if(@recipe.save)

      flash[:success] = 'Your recipe was created successfully!'
      redirect_to recipes_path
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = 'The recipe was updated successfully'
      redirect_to recipe_path(@recipe)
    else
      render :edit
    end
  end

  def like
    like = Like.create(like: params[:like], chef: current_user, recipe: @recipe)
    if like.valid?
      flash[:success] = 'Your selection was successful'
      redirect_to :back
    else
      flash[:danger] = 'You can only like/dislike a recipe once'
      redirect_to :back
    end
  end

  def destroy
    Recipe.find(params[:id]).destroy
    flash[:success] = 'Recipe Deleted'
    redirect_to recipes_path
  end

  private
  def recipe_params
    params.require(:recipe).permit(:name, :summary, :description, :picture, style_ids: [], ingredient_ids: [])
  end

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def require_same_user
    if current_user != @recipe.chef && !current_user.admin?
      flash[:danger] = 'You can only edit your own recipes'
      redirect_to recipes_path
    end
  end

  def require_user_like
    if !logged_in?
      flash[:danger] = 'You must be logged in to perform that action!'
      redirect_to :back
    end
  end

  def admin_user
    redirect_to recipes_path unless current_user.admin?
  end

end

app/controllers/styles_controller.rb
class StylesController < ApplicationController
  before_action :require_user, except: [:show]

  def show
    @style = Style.find(params[:id])
    @recipes = @style.recipes.paginate(page: params[:page], per_page: 4)
  end

  def new
    @style = Style.new
  end

  def create
    @style = Style.new(style_params)
    if @style.save
      flash[:success] = 'Style was created successfully'
      redirect_to recipes_path
    else
      render 'new'
    end
  end

  private
  def style_params
    params.require(:style).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def gravatar_for(chef, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(chef.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: chef.chefname, class: "gravatar")
  end
end

app/views/chefs/_form.html.erb
<%= render 'shared/errors', obj: @chef %>

<div class="row">
  <div class="card col-md-8 col-md-offset-2">
    <%= form_for @chef do |f| %>
      <%= f.label :chefname %>
        <%= f.text_field :chefname %>

        <%= f.label :email %>
        <%= f.email_field :email %>

        <%= f.label :password %>
        <%= f.password_field :password %>

        <%= f.submit(@chef.new_record? ? 'Register' : 'Edit Profile', class: "btn btn-success") %>
    <% end %>
  </div>
</div>

app/views/chefs/edit.html.erb
<%= render 'shared/page_title', title: "Edit your profile" %>

<%= render 'form' %>

app/views/chefs/index.html.erb
<%= render 'shared/page_title', title: 'All Chefs' %>
<ul class="nav nav-tabs">
  <li>
    <%= link_to 'Recipes', recipes_path, class: 'nav-link' %>
  </li>
  <li class='active'>
    <%= link_to 'Chefs', chefs_path, class: 'nav-link active' %>
  </li>
</ul>


<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= will_paginate %>
  </div>
</div>

<% @chefs.each do |chef| %>
  <div class="row">
    <div class="col-md-4 col-md-offset-4 center">
      <%= link_to gravatar_for(chef, size: 200), chef_path(chef) %>
      <p>
        <h5>Chef name: <%= chef.chefname %></h5>
      </p>
    </div>
  </div>
<% end %>

app/views/chefs/new.html.erb
<%= render 'shared/page_title', title: "Register your account" %>

<%= render 'form' %>

app/views/chefs/show.html.erb
<%= render 'shared/page_title', title: 'Chef: ' + @chef.chefname %>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= gravatar_for @chef, size: 200 %>
    <hr />
  </div>
</div>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <h3><em>Recipes</em></h3>
    <%= will_paginate @recipes %>
  </div>
</div>

<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="col-md-8 card col-md-offset-2">

      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <p>
        <span class="quiet"><small> created: <%= time_ago_in_words(recipe.created_at) %> ago, </small></span>
        <span class="quiet"><small> updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
      </p>
        <div class="pull-right">
          <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="fa fa-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total
          %><% end %> &nbsp&nbsp&nbsp&nbsp
          <%= link_to like_recipe_path(recipe, like: false), method: :post do %> <i class="fa fa-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %> <% end %>
        </div>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-md-4 col-md-offset-4 center">
    <%= will_paginate @recipes %>
  </div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class="quiet"><%= link_to ingredient.name, ingredient_path(ingredient) %>&nbsp</span>

app/views/ingredients/new.html.erb
<%= render 'shared/page_title', title: 'Create a new Ingredient' %>

<%= render 'shared/errors', obj: @ingredient %>

<div class="row">
  <div class="card col-md-8 col-md-offset-2">
    <%= form_for @ingredient do |f| %>
        <%= f.label :name  %>
        <%= f.text_field :name %>

        <%= f.submit 'Create Ingredient', class: 'btn btn-success' %>

    <% end  %>

  </div>
</div>

app/views/ingredients/show.html.erb
<%= render 'shared/page_title', title: 'Recipes for: ' + @ingredient.name%>

<ul class="nav nav-tabs">
  <li class="nav-item nav-link-active">
    <%= link_to 'Recipes', recipes_path, class: 'nav-link active' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Chefs', chefs_path, class: 'nav-link' %>
  </li>
</ul>

<%= will_paginate @recipes %>

<% @ingredient.recipes.each do |recipe| %>
    <div class="row">
      <div class="col-md-2">
        <section class="chef_info center">
          <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
          <h5>Chef name: <%= recipe.chef.chefname %></h5>
        </section>
      </div>

      <div class="col-md-5 card">
        <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
        <p><%= recipe.summary %></p>
        <p>Style: <%= render recipe.styles %></p>
        <p>Ingredients: <%= render recipe.ingredients %></p>
        <p>
          <span class='quiet'><small>created <%= time_ago_in_words(recipe.created_at) %> ago</small></span>,
          <span class='quiet'><small> updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
        </p>

        <div class="pull-right">
          <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
              <i class="fa fa-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
          <% end %>
          <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
              <i class="fa fa-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
          <% end %>
        </div>

      </div>

      <div class="col-md-4">
        <%= image_tag(recipe.picture.url, size: '250x150', class: 'gravatar') if recipe.picture? %>
      </div>
    </div>

    </div>
    <hr>
<% end %>

<%= will_paginate @recipes %>

app/views/layouts/_footer.html.erb
<footer class="container-fluid">
  <p>&copy; MyRecipes 2015</p>
</footer>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-md-12">
    <% flash.each do |message_type, message| %>
      <div class="card alert alert-<%= message_type %>">
        <%= message %>
        <a class="close" data-dismiss="alert">&#215;</a>
      </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<header>
  <div class="container-fluid">
    <div class="row">

      <!-- BEGIN NAV-->
      <nav class="navbar navbar-fixed-top navbar-default">
        <!-- BRAND -->
        <%= link_to 'Recipes', root_path, class: 'navbar-brand btn btn-lg btn-success', id: 'logo'  %>
        <!-- END BRAND -->
        <!-- NAVBAR LINKS-->
        <ul class="nav navbar-nav">

          <% if logged_in? %>
              <li class="nav_item"><%= link_to 'Create New Recipe', new_recipe_path, class: 'nav-link btn btn-default btn-warning' %></li>
          <% end %>

          <ul class="nav_ul_item">
            <li class="dropdown">
              <%= link_to '#', class: 'btn btn-default btn-danger dropdown-toggle', 'data-toggle' => 'dropdown' do %>
                  Styles <b class="caret"></b>
              <% end %>
              <ul class="dropdown-menu">
                <% Style.all.each do |style| %>
                  <li><%= link_to style.name, style_path(style) %></li>
                <% end %>
                <% if logged_in? %>
                  <hr>
                  <!--<li class="divider"></li>-->
                  <li>
                    <%= link_to(new_style_path) do %>
                     New Style
                    <% end %>
                  </li>
                <% end %>
              </ul>
            </li>
          </ul>

          <ul class="nav_ul_item">
            <li class="dropdown">
              <%= link_to '#', class: 'btn btn-default btn-danger dropdown-toggle', 'data-toggle' => 'dropdown' do %>
                  Ingredients <b class="caret"></b>
              <% end %>
              <ul class="dropdown-menu">
                <% Ingredient.all.each do |ingredient| %>
                    <li><%= link_to ingredient.name, ingredient_path(ingredient) %></li>
                <% end %>
                <% if logged_in? %>
                    <hr>
                    <li>
                      <%= link_to(new_ingredient_path) do %>
                        New Ingredient
                      <% end %>
                    </li>
                <% end %>
              </ul>
            </li>
          </ul>


          <% if logged_in? %>
              <ul class="nav_ul_item">
                <li class="dropdown">
                  <%= link_to '#', class: 'btn btn-default btn-danger dropdown-toggle', 'data-toggle' => 'dropdown' do %>
                    <%= current_user.chefname %> - Settings<b class="caret"></b>
                  <% end %>
                  <ul class="dropdown-menu">
                    <li><%= link_to 'View Profile', chef_path(current_user) %></li>
                    <li><%= link_to 'Edit Profile', edit_chef_path(current_user) %></li>
                    <li class="divider"></li>
                    <li><%= link_to "Log Out", logout_path %></li>
                  </ul>
                </li>
              </ul>
            <% else %>
              <li class="nav_item">
                <%= link_to 'Log In', login_path, class: 'nav-link btn btn-default btn-success' %>
              </li>
            <% end %>


      <!-- END NAV -->
        </ul>
      </nav>
      <!-- END NAV -->

    </div>
  </div>
  <!-- END BOOTSTRAP POS-->
</header>
<!-- ****** END HEADER *******-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RecipesApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navigation' %>

<div class="container-fluid">
  <%= render 'layouts/messages' %>
  <%= yield %>
</div>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/logins/new.html.erb
<%= render 'shared/page_title', title: 'Log in' %>


<div class="row">
  <div class="card col-md-5 col-md-offset-4">
    <%= form_tag '/login' do %>

    <%= label_tag :email %>
    <%= text_field_tag :email %>

    <%= label_tag :password %>
    <%= password_field_tag :password %>

    <%= submit_tag 'Login', class: 'btn btn-success' %>
    <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to MyRecipes App</h1>

  <h2>Please post your recipes!</h2>

  <%= link_to 'Sign up now!', register_path, class: 'btn btn-lg btn-success' %>
</div>


<div class="row">
  <div class="col-md-4">
    <h3 class="midrow">
      View Recipes as Guest User
    </h3>
    <h2 class="left">Browse and view recipes as a guest and Sign up later</h2>
    <p><%= link_to 'Browse Recipe Listings', recipes_path, class: 'btn btn-warning btn-small' %></p>
  </div>

  <div class="col-md-4">
    <h3 class="midrow">
      Sign in to your account
    </h3>
    <h2 class="left">Add/update your recipes, create reviews, like/dislike recipes and much, much more!</h2>
    <p><%= link_to 'Log-in to your account', login_path, class: 'btn btn-warning btn-small' %></p>
  </div>


  <div class="col-md-4">
    <h3 class="midrow">
      View Recipes as Guest User
    </h3>
    <h2 class="left">Browse and view recipes as a guest and Sign up later</h2>
    <p><%= link_to 'Browse Recipe Listings', '', class: 'btn btn-warning btn-small' %></p>
  </div>
</div>

app/views/recipes/edit.html.erb
<%= render 'shared/page_title', title: 'Edit the Recipe' %>

<%= render 'form' %>

app/views/recipes/index.html.erb
<%= render 'shared/page_title', title: 'All Recipes' %>

<ul class="nav nav-tabs">
  <li class="active">
    <%= link_to 'Recipes', recipes_path, class: 'nav-link active' %>
  </li>
  <li>
    <%= link_to 'Chefs', chefs_path, class: 'nav-link' %>
  </li>
</ul>

<%= will_paginate %>

<% @recipes.each do |recipe| %>
  <div class="row">
    <div class="col-md-2">
      <section class="chef_info center">
        <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
        <h5>Chef name: <%= recipe.chef.chefname %></h5>
      </section>
    </div>

    <div class="col-md-5 well">
      <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
      <p><%= recipe.summary %></p>
      <% if recipe.styles.any? %>
        <p>Style: <%= render recipe.styles %></p>
      <% end %>
      <% if recipe.ingredients.any? %>
        <p>Ingredients: <%= render recipe.ingredients %></p>
      <% end %>
      <p>
        <span class='quiet'><small>created <%= time_ago_in_words(recipe.created_at) %> ago</small></span>,
        <span class='quiet'><small> updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
      </p>

      <div class="pull-right">
        <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
          <i class="fa fa-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
        <% end %>
        <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
          <i class="fa fa-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
        <% end %>
      </div>

    </div>



    <div class="col-md-4">
      <%= image_tag(recipe.picture.url, size: '250x150', class: 'gravatar') if recipe.picture? %>
    </div>
  </div>

  </div>
  <hr>
<% end %>

<%= will_paginate %>

app/views/recipes/new.html.erb
<%= render 'shared/page_title', title: 'Create a new Recipe' %>

<%= render 'form' %>

app/views/recipes/show.html.erb
<%= render 'shared/page_title', title: @recipe.name %>

<div class="row">
  <div class="col-md-4 pull-right center">
    <%= link_to gravatar_for(@recipe.chef, size: 200), chef_path(@recipe.chef) %>
    <p>
      <h5>Brought to you by: <%= @recipe.chef.chefname %></h5>
    </p>
  </div>
  <div class="col-md-8">
    <% if logged_in? && (@recipe.chef == current_user || current_user.admin?) %>
      <%= link_to 'Edit this recipe', edit_recipe_path(@recipe), class: "btn btn-success pull-right" %>
    <% end %>

    <% if logged_in? && (@recipe.chef == current_user || current_user.admin?) %>
        <%= link_to '[Delete Recipe]', @recipe, method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %>
    <% end %>
    <h3><%= @recipe.summary %></h3>
    <div class="show_recipe">
      <%= image_tag(@recipe.picture.url, class: 'gravatar') if @recipe.picture? %>
    </div>

    <div class="well">
      <% if @recipe.styles.any? %>
        <p>Styles: <%= render @recipe.styles %></p>
      <% end %>
      <% if @recipe.ingredients.any? %>
        <p>Ingredients: <%= render @recipe.ingredients %></p>
      <% end %>
      <p>
        <strong>Steps:</strong>
      </p>
      <%= simple_format(@recipe.description) %>
      <div class="pull-right">
        <%= link_to like_recipe_path(@recipe, like: true), method: :post do %>
            <i class="fa fa-thumbs-up"></i> &nbsp <%= @recipe.thumbs_up_total %>
        <% end %>
        &nbsp&nbsp&nbsp&nbsp&nbsp
        <%= link_to like_recipe_path(@recipe, like: false), method: :post do %>
          <i class="fa fa-thumbs-down"></i> &nbsp <%= @recipe.thumbs_down_total %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<h5><%= link_to 'Return to Recipes Listing', recipes_path, class: 'btn btn-warning btn-small' %></h5>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
    <div class="row">
      <div class="alert alert-danger col-md-8 col-md-offset-2">
        <h5>Please correct the following errors:</h5>
        <% obj.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
      </div>
    </div>
<% end %>

app/views/shared/_page_title.html.erb
<p>
  <h1><%= title %></h1>
  <hr/>
</p>

app/views/styles/_style.html.erb
<span class="quiet"><%= link_to style.name, style_path(style) %>&nbsp</span>

app/views/styles/new.html.erb
<%= render 'shared/page_title', title: 'Create a new Style' %>

<%= render 'shared/errors', obj: @style %>

<div class="row">
  <div class="card col-md-8 col-md-offset-2">
    <%= form_for @style do |f| %>
        <%= f.label :name  %>
        <%= f.text_field :name %>

        <%= f.submit 'Create Style', class: 'btn btn-success' %>

    <% end  %>

  </div>
</div>

app/views/styles/show.html.erb
<%= render 'shared/page_title', title: 'Recipes for: ' + @style.name + ' food' %>

<ul class="nav nav-tabs">
  <li class="nav-item nav-link-active">
    <%= link_to 'Recipes', recipes_path, class: 'nav-link active' %>
  </li>
  <li class="nav-item">
    <%= link_to 'Chefs', chefs_path, class: 'nav-link' %>
  </li>
</ul>

<%= will_paginate @recipes %>

<% @style.recipes.each do |recipe| %>
    <div class="row">
      <div class="col-md-2">
        <section class="chef_info center">
          <%= link_to gravatar_for(recipe.chef, size: 100), chef_path(recipe.chef) %>
          <h5>Chef name: <%= recipe.chef.chefname %></h5>
        </section>
      </div>

      <div class="col-md-5 card">
        <h4><%= link_to recipe.name, recipe_path(recipe) %></h4>
        <p><%= recipe.summary %></p>
        <p>Style: <%= render recipe.styles %></p>
        <p>Ingredients: <%= render recipe.ingredients %></p>
        <p>
          <span class='quiet'><small>created <%= time_ago_in_words(recipe.created_at) %> ago</small></span>,
          <span class='quiet'><small> updated: <%= time_ago_in_words(recipe.updated_at) %> ago</small></span>
        </p>

        <div class="pull-right">
          <%= link_to like_recipe_path(recipe, like: true), method: :post do %>
              <i class="fa fa-thumbs-up"></i> &nbsp <%= recipe.thumbs_up_total %>
          <% end %>
          <%= link_to like_recipe_path(recipe, like: false), method: :post do %>
              <i class="fa fa-thumbs-down"></i> &nbsp <%= recipe.thumbs_down_total %>
          <% end %>
        </div>

      </div>

      <div class="col-md-4">
        <%= image_tag(recipe.picture.url, size: '250x150', class: 'gravatar') if recipe.picture? %>
      </div>
    </div>

    </div>
    <hr>
<% end %>

<%= will_paginate @recipes %>